from pathlib import Path
root = Path(__file__).resolve().parents[1]
repls = {
'slides/source-faithful/14-analytics-definition.tex': [(r'\includegraphics[width=162bp,height=61.047bp]{assets/visuals/lecture-1/informs-analytics-definition-logo.png}', r'\href{https://www.informs.org/Explore/Operations-Research-Analytics}{\includegraphics[width=162bp,height=61.047bp]{assets/visuals/lecture-1/informs-analytics-definition-logo.png}}'), (r'\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (880.898,-499.702)', r'\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (286,-388) {{\ArialFont\fontsize{9}{11}\selectfont\color{c7F7F7F}\href{https://www.informs.org/Explore/Operations-Research-Analytics}{Definition adapted from INFORMS.}}};\n\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (880.898,-499.702)')],
'slides/source-faithful/16-covid-descriptive.tex': [(r'\includegraphics[width=515.963bp,height=364.209bp]{assets/visuals/lecture-1/covid-descriptive-analytics-case.png}', r'\href{https://ourworldindata.org/coronavirus}{\includegraphics[width=515.963bp,height=364.209bp]{assets/visuals/lecture-1/covid-descriptive-analytics-case.png}}'), (r'\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (880.898,-499.702)', r'\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (104,-343) {{\ArialFont\fontsize{9}{11}\selectfont\color{c7F7F7F}\href{https://ourworldindata.org/coronavirus}{Historical COVID-19 example; current data and source details: Our World in Data.}}};\n\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (880.898,-499.702)')],
'slides/source-faithful/18-covid-predictive.tex': [(r'\includegraphics[width=680.39bp,height=357.205bp]{assets/visuals/lecture-1/covid-predictive-analytics-case.png}', r'\href{https://epirisk.net/}{\includegraphics[width=680.39bp,height=357.205bp]{assets/visuals/lecture-1/covid-predictive-analytics-case.png}}'), (r'\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (880.898,-499.702)', r'\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (80,-425) {{\ArialFont\fontsize{9}{11}\selectfont\color{c7F7F7F}\href{https://epirisk.net/}{Historical scenario visual: EpiRisk. Explore current assumptions and outputs online.}}};\n\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (880.898,-499.702)')],
'slides/source-faithful/19-covid-prescriptive.tex': [(r'\includegraphics[width=563.738bp,height=296.667bp]{assets/visuals/lecture-1/covid-prescriptive-analytics-case.png}', r'\href{https://doi.org/10.1007/s10729-020-09542-0}{\includegraphics[width=563.738bp,height=296.667bp]{assets/visuals/lecture-1/covid-prescriptive-analytics-case.png}}'), (r'Source: Bertsimas et al. (2020)', r'Source: \href{https://doi.org/10.1007/s10729-020-09542-0}{Bertsimas et al. (2020)}')],
'slides/source-faithful/36-dark-side.tex': [(r'\includegraphics[width=295.916bp,height=453.594bp]{assets/visuals/lecture-1/slide-37-dark-side-of-analytics-visual-01.png}', r'\href{https://weaponsofmathdestructionbook.com/}{\includegraphics[width=295.916bp,height=453.594bp]{assets/visuals/lecture-1/slide-37-dark-side-of-analytics-visual-01.png}}'), (r'\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (880.898,-499.702)', r"\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (55,-438) {{\ArialFont\fontsize{9}{11}\selectfont\color{c7F7F7F}\href{https://weaponsofmathdestructionbook.com/}{Cover: Cathy O'Neil, \emph{Weapons of Math Destruction} (2016).}}};\n\node[anchor=north west,inner sep=0pt,outer sep=0pt] at (880.898,-499.702)")],
}
for rel, pairs in repls.items():
    path = root / rel
    s = path.read_text(encoding='utf-8')
    for a,b in pairs:
        if a not in s:
            raise RuntimeError(f'Missing expected text in {rel}: {a[:48]}')
        s = s.replace(a,b,1)
    path.write_text(s,encoding='utf-8')
print('Updated', len(repls), 'source-faithful slides')
